// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD1qYeRhaNwqKKfYbdBnlAYm4wbU0ufs44',
    appId: '1:299235662184:web:a945a882e25214d9e41edd',
    messagingSenderId: '299235662184',
    projectId: 'task-management-app-goteri141',
    authDomain: 'task-management-app-goteri141.firebaseapp.com',
    storageBucket: 'task-management-app-goteri141.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQyf3S4FMBVEsg1cgdD_PEev7KG84HppM',
    appId: '1:299235662184:android:a0831eb4e2c8bcd6e41edd',
    messagingSenderId: '299235662184',
    projectId: 'task-management-app-goteri141',
    storageBucket: 'task-management-app-goteri141.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB9lGGqYhvaTGOYMDgn2McGbqWqVnxSL0',
    appId: '1:299235662184:ios:661e56f3f1dd7971e41edd',
    messagingSenderId: '299235662184',
    projectId: 'task-management-app-goteri141',
    storageBucket: 'task-management-app-goteri141.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB9lGGqYhvaTGOYMDgn2McGbqWqVnxSL0',
    appId: '1:299235662184:ios:661e56f3f1dd7971e41edd',
    messagingSenderId: '299235662184',
    projectId: 'task-management-app-goteri141',
    storageBucket: 'task-management-app-goteri141.firebasestorage.app',
    iosBundleId: 'com.example.taskManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD1qYeRhaNwqKKfYbdBnlAYm4wbU0ufs44',
    appId: '1:299235662184:web:c1dd08a237d56580e41edd',
    messagingSenderId: '299235662184',
    projectId: 'task-management-app-goteri141',
    authDomain: 'task-management-app-goteri141.firebaseapp.com',
    storageBucket: 'task-management-app-goteri141.firebasestorage.app',
  );
}
